export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_LIST_ERROR = 'GET_USER_LIST_ERROR';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';

export const REMOVE_USER = 'REMOVE_USER';
export const REMOVE_USER_ERROR = 'REMOVE_USER_ERROR';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';

