export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_USER_DETAIL_ERROR = 'GET_USER_DETAIL_ERROR';
export const GET_USER_DETAIL_SUCCESS = 'GET_USER_DETAIL_SUCCESS';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

